// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoZxexActd7zuc3730ZkL6YWv8G8L3pn8',
    appId: '1:946050960770:web:23bafc598ed31e2d04939b',
    messagingSenderId: '946050960770',
    projectId: 'meetin-25',
    authDomain: 'meetin-25.firebaseapp.com',
    storageBucket: 'meetin-25.firebasestorage.app',
    measurementId: 'G-7V1MQ05FCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQaLssgh_jPBvTi5E1W1vONbWreOZI4gw',
    appId: '1:946050960770:android:bcac91b783bdc62e04939b',
    messagingSenderId: '946050960770',
    projectId: 'meetin-25',
    storageBucket: 'meetin-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS20vFptlYA4h3DMV1TDG0cmPM86p2xY4',
    appId: '1:946050960770:ios:6c13b2ab28892a4004939b',
    messagingSenderId: '946050960770',
    projectId: 'meetin-25',
    storageBucket: 'meetin-25.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS20vFptlYA4h3DMV1TDG0cmPM86p2xY4',
    appId: '1:946050960770:ios:6c13b2ab28892a4004939b',
    messagingSenderId: '946050960770',
    projectId: 'meetin-25',
    storageBucket: 'meetin-25.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoZxexActd7zuc3730ZkL6YWv8G8L3pn8',
    appId: '1:946050960770:web:08ccae847399e88204939b',
    messagingSenderId: '946050960770',
    projectId: 'meetin-25',
    authDomain: 'meetin-25.firebaseapp.com',
    storageBucket: 'meetin-25.firebasestorage.app',
    measurementId: 'G-TMDVBTXXQH',
  );
}
